import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const robot = Roboto({
  weight: "400",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by Arman Mia",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robot.className}>
        <main className="min-h-dvh">{children}</main>
      </body>
    </html>
  );
}
